[2025-04-24T08:02:09.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T08:02:09.837+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_images_collector.fetch_traffic_data scheduled__2025-04-24T07:35:00+00:00 [queued]>
[2025-04-24T08:02:09.849+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_images_collector.fetch_traffic_data scheduled__2025-04-24T07:35:00+00:00 [queued]>
[2025-04-24T08:02:09.850+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 4
[2025-04-24T08:02:09.864+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): fetch_traffic_data> on 2025-04-24 07:35:00+00:00
[2025-04-24T08:02:09.876+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=615) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-24T08:02:09.882+0000] {standard_task_runner.py:72} INFO - Started process 626 to run task
[2025-04-24T08:02:09.883+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'traffic_images_collector', 'fetch_traffic_data', 'scheduled__2025-04-24T07:35:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/traffic_images_collector.py', '--cfg-path', '/tmp/tmp3jf4gvce']
[2025-04-24T08:02:09.885+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask fetch_traffic_data
[2025-04-24T08:02:10.020+0000] {task_command.py:467} INFO - Running <TaskInstance: traffic_images_collector.fetch_traffic_data scheduled__2025-04-24T07:35:00+00:00 [running]> on host d8cd43aac9c4
[2025-04-24T08:02:10.187+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_images_collector' AIRFLOW_CTX_TASK_ID='fetch_traffic_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T07:35:00+00:00'
[2025-04-24T08:02:10.191+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-24T08:02:10.192+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-24T08:02:10.192+0000] {logging_mixin.py:190} INFO - Current task name:fetch_traffic_data state:running start_date:2025-04-24 08:02:09.837999+00:00
[2025-04-24T08:02:10.193+0000] {logging_mixin.py:190} INFO - Dag name:traffic_images_collector and current dag run status:running
[2025-04-24T08:02:10.193+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-24T08:02:10.194+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/traffic_images_collector.py", line 58, in fetch_traffic_data
    raise Exception("API key not found in Airflow connection extras")
Exception: API key not found in Airflow connection extras
[2025-04-24T08:02:10.214+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-24T08:02:10.215+0000] {logging_mixin.py:190} INFO - Task start:2025-04-24 08:02:09.837999+00:00 end:2025-04-24 08:02:10.213602+00:00 duration:0.375603
[2025-04-24T08:02:10.215+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): fetch_traffic_data> dag:<DAG: traffic_images_collector> dagrun:<DagRun traffic_images_collector @ 2025-04-24 07:35:00+00:00: scheduled__2025-04-24T07:35:00+00:00, state:running, queued_at: 2025-04-24 07:40:00.410012+00:00. externally triggered: False>
[2025-04-24T08:02:10.216+0000] {logging_mixin.py:190} INFO - Failure caused by API key not found in Airflow connection extras
[2025-04-24T08:02:10.217+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=traffic_images_collector, task_id=fetch_traffic_data, run_id=scheduled__2025-04-24T07:35:00+00:00, execution_date=20250424T073500, start_date=20250424T080209, end_date=20250424T080210
[2025-04-24T08:02:10.249+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-24T08:02:10.249+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task fetch_traffic_data (API key not found in Airflow connection extras; 626)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/traffic_images_collector.py", line 58, in fetch_traffic_data
    raise Exception("API key not found in Airflow connection extras")
Exception: API key not found in Airflow connection extras
[2025-04-24T08:02:10.299+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T08:02:10.330+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T08:02:10.332+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
