[2025-04-24T13:43:21.144+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T13:43:21.179+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_images_collector.get_api_key scheduled__2025-04-24T13:35:00+00:00 [queued]>
[2025-04-24T13:43:21.194+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_images_collector.get_api_key scheduled__2025-04-24T13:35:00+00:00 [queued]>
[2025-04-24T13:43:21.195+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-24T13:43:21.216+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): get_api_key> on 2025-04-24 13:35:00+00:00
[2025-04-24T13:43:21.235+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-04-24T13:43:21.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'traffic_images_collector', 'get_api_key', 'scheduled__2025-04-24T13:35:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/traffic_images_collector.py', '--cfg-path', '/tmp/tmpb83jzcp7']
[2025-04-24T13:43:21.243+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask get_api_key
[2025-04-24T13:43:21.323+0000] {task_command.py:467} INFO - Running <TaskInstance: traffic_images_collector.get_api_key scheduled__2025-04-24T13:35:00+00:00 [running]> on host 59b5c23bc6da
[2025-04-24T13:43:21.495+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_images_collector' AIRFLOW_CTX_TASK_ID='get_api_key' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T13:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T13:35:00+00:00'
[2025-04-24T13:43:21.498+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-24T13:43:21.499+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-24T13:43:21.501+0000] {logging_mixin.py:190} INFO - Current task name:get_api_key state:running start_date:2025-04-24 13:43:21.181708+00:00
[2025-04-24T13:43:21.502+0000] {logging_mixin.py:190} INFO - Dag name:traffic_images_collector and current dag run status:running
[2025-04-24T13:43:21.504+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-24T13:43:21.533+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/traffic_images_collector.py", line 28, in get_api_key
    connection = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `lta_api_connection` isn't defined
[2025-04-24T13:43:21.552+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-24T13:43:21.554+0000] {logging_mixin.py:190} INFO - Task start:2025-04-24 13:43:21.181708+00:00 end:2025-04-24 13:43:21.551893+00:00 duration:0.370185
[2025-04-24T13:43:21.555+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): get_api_key> dag:<DAG: traffic_images_collector> dagrun:<DagRun traffic_images_collector @ 2025-04-24 13:35:00+00:00: scheduled__2025-04-24T13:35:00+00:00, state:running, queued_at: 2025-04-24 13:43:04.802380+00:00. externally triggered: False>
[2025-04-24T13:43:21.557+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `lta_api_connection` isn't defined
[2025-04-24T13:43:21.558+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=traffic_images_collector, task_id=get_api_key, run_id=scheduled__2025-04-24T13:35:00+00:00, execution_date=20250424T133500, start_date=20250424T134321, end_date=20250424T134321
[2025-04-24T13:43:21.607+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-24T13:43:21.610+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task get_api_key (The conn_id `lta_api_connection` isn't defined; 87)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/traffic_images_collector.py", line 28, in get_api_key
    connection = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `lta_api_connection` isn't defined
[2025-04-24T13:43:21.655+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T13:43:21.698+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T13:43:21.702+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
